# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fashop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'RCTAnimation',
    'RCTBlob',
    'DevSupport'
  ]

  # Pods for fashop

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  # pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  # pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  # pod 'JPushRN', :path => '../node_modules/jpush-react-native'

  # pod 'JCoreRN', :path => '../node_modules/jcore-react-native'

  target 'fashopTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fashop-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fashop-tvOS

  target 'fashop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
