// export const domain = 'http://temp.chitj.com/haoyouhui';
// export const domain = 'http://192.168.1.115/haoyouhui';
// export const domain = 'http://www.haoyouhui2016.com';
// export const domain = 'http://temp.chitj.com/jingjiren';
import { env, developer } from './APP_ROOT_CONFIG';

const { domain, mockDomain } = env

const ROOT_URL = `${domain}/server/`;
const ROOT_URL1 = `${domain}/Api/`;
const ROOT_URL2 = `${domain}/app/`;
const MOCK_ROOT_URL = `${mockDomain}/`;

/*
 *  1.如果你还没有在root_config中加入你的开发者信息，那你需要去添加developer
 *	2.如果你已经添加了developer信息，那么在添加接口的时候需要定义接口的使用者(developer属性名)
 *	3.对应定义你的开发者昵称
 *	例: const girl1 = 'xxx';
*/

const girl1 = 'liujinmeng';

export const API_URL = {
	SHOPINFO: {
		domain: ROOT_URL,
		apiUrl: 'shop/info',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}shop/info`,
		remark: '店铺基础配置信息',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
	},
	PAGEPORTAL: {
		domain: ROOT_URL,
		apiUrl: 'page/portal',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}page/portal`,
		remark: '首页样式',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}page/portal`,
	},
	GOODSCATEGORYLIST: {
		apiUrl: 'goodscategory/list',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}goodscategory/list`,
		method: 'GET',
		needLogin: false,
		remark: '商品分类列表',
		showLoading: false,
		tableName: 'ez_store',
	},
	SORTCONTENTLIST: {
		apiUrl: 'goodscategory/info',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}goodscategory/info`,
		method: 'GET',
		needLogin: false,
		remark: '第三分类下边的列表',
		showLoading: false,
		tableName: 'ez_store',
	},
	GOODSINFO: {
		domain: ROOT_URL,
		apiUrl: 'goods/info',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}goods/info`,
		remark: '商品详情',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}goods/info`,
	},
	GOODSEVALUATELIST: {
		domain: ROOT_URL,
		apiUrl: 'goods/evaluateList',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}goods/evaluateList`,
		remark: '商品评价',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}goods/evaluateList`,
	},
	SHOPCARTDATA: {
		apiUrl: 'shopCart/shopCarts',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}shopCart/shopCarts`,
		method: 'GET',
		mock: true,
		mockFetchUrl: `${MOCK_ROOT_URL}shopCart/shopCarts`,
		needLogin: false,
		remark: '购物车列表',
		showLoading: false,
		tableName: 'ez_store',
	},
	GOODSDATALIST: {
		apiUrl: 'goods/list',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}goods/list`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}goods/list`,
		needLogin: false,
		remark: '商品列表',
		showLoading: false,
		tableName: 'ez_store',
	},
	SHOPCARTADDG: {
		apiUrl: 'cart/add',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}cart/add`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}cart/add`,
		needLogin: false,
		remark: '购物车添加',
		showLoading: false,
		tableName: 'ez_store',
	},
	SHOPCARTEDITG: {
		apiUrl: 'cart/edit',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}cart/edit`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}cart/edit`,
		needLogin: false,
		remark: '购物车修改',
		showLoading: false,
		tableName: 'ez_store',
	},
	SHOPCARTEXISTG: {
		apiUrl: 'cart/exist',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}cart/exist`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}cart/exist`,
		needLogin: false,
		remark: '购物车存在',
		showLoading: false,
		tableName: 'ez_store',
	},
	SHOPCARTDElG: {
		apiUrl: 'cart/del',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}cart/del`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}cart/del`,
		needLogin: false,
		remark: '购物车删除',
		showLoading: false,
		tableName: 'ez_store',
	},
	SHOPCARTCLEARG: {
		apiUrl: 'cart/clear',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}cart/clear`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}cart/clear`,
		needLogin: false,
		remark: '购物车清空',
		showLoading: false,
		tableName: 'ez_store',
	},
	SHOPCARTTOTALNUMG: {
		apiUrl: 'cart/totalNum',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}cart/totalNum`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}cart/totalNum`,
		needLogin: false,
		remark: '购物车数量',
		showLoading: false,
		tableName: 'ez_store',
	},
	GOODSEVALUATEINTER: {
		apiUrl: 'goodsevaluate/list',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}goodsevaluate/list`,
		method: 'GET',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}goodsevaluate/list`,
		needLogin: false,
		remark: '商品评价',
		showLoading: false,
		tableName: 'ez_store',
	},
	GOODSEVALUATEORDER: {
		apiUrl: 'goodsevaluate/add',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}goodsevaluate/add`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}goodsevaluate/add`,
		needLogin: false,
		remark: '对订单商品评价',
		showLoading: false,
		tableName: 'ez_store',
	},
	GOODSEVALUATEAPPEND: {
		apiUrl: 'goodsevaluate/append',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}goodsevaluate/append`,
		method: 'POST',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}goodsevaluate/append`,
		needLogin: false,
		remark: '对订单商品评价',
		showLoading: false,
		tableName: 'ez_store',
	},
	GOODSEVALUATEDETILE: {
		apiUrl: 'goodsevaluate/detail',
		author: '孙泉',
		developer: girl1,
		domain: ROOT_URL,
		fetchUrl: `${ROOT_URL}goodsevaluate/detail`,
		method: 'GET',
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}goodsevaluate/detail`,
		needLogin: false,
		remark: '我的评价列表',
		showLoading: false,
		tableName: 'ez_store',
	},
	// ******** User ********
	USERLOGIN: {
		domain: ROOT_URL,
		apiUrl: 'user/login',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}user/login`,
		remark: '登录',
		method: 'POST',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}user/login`,
	},
	USERREGISTER: {
		domain: ROOT_URL,
		apiUrl: 'user/register',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}user/register`,
		remark: '注册',
		method: 'POST',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}user/register`,
	},
	VERIFYCODEADD: {
		domain: ROOT_URL,
		apiUrl: 'Verifycode/add',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}Verifycode/add`,
		remark: '发送验证码',
		method: 'POST',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}Verifycode/add`,
	},
	USERSELF: {
		domain: ROOT_URL,
		apiUrl: 'user/self',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}user/self`,
		remark: '用户信息',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}user/self`,
	},
	INITUSERSELF: {
		domain: ROOT_URL,
		apiUrl: 'user/self',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}user/self`,
		remark: '初始用户信息',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}user/self`,
	},
	USERLOGOUT: {
		domain: ROOT_URL,
		apiUrl: 'user/logout',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}user/logout`,
		remark: '退出',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}user/logout`,
	},
	USEREDITPASSWORD: {
		domain: ROOT_URL,
		apiUrl: 'user/editPassword',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}user/editPassword`,
		remark: '修改密码',
		method: 'POST',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}user/editPassword`,
	},
	USEREDITPASSWORDBYFIND: {
		domain: ROOT_URL,
		apiUrl: 'user/editPasswordByFind',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}user/editPasswordByFind`,
		remark: '找回密码',
		method: 'POST',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}user/editPasswordByFind`,
	},
	// ******** Address ********
	AREALIST: {
		domain: ROOT_URL,
		apiUrl: 'area/list',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}area/list`,
		remark: '地区列表',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: false,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}area/list`,
	},
	ADDRESSLIST: {
		domain: ROOT_URL,
		apiUrl: 'address/list',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}address/list`,
		remark: '收货地址列表',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}address/list`,
	},
	ADDRESSINFO: {
		domain: ROOT_URL,
		apiUrl: 'address/info',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}address/info`,
		remark: '地址详情',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}address/info`,
	},
	ADDRESSADD: {
		domain: ROOT_URL,
		apiUrl: 'address/add',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}address/add`,
		remark: '收货地址添加',
		method: 'POST',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}address/add`,
	},
	ADDRESSEDIT: {
		domain: ROOT_URL,
		apiUrl: 'address/edit',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}address/edit`,
		remark: '收货地址修改',
		method: 'POST',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}address/edit`,
	},
	ADDRESSDEL: {
		domain: ROOT_URL,
		apiUrl: 'address/del',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}address/del`,
		remark: '收货地址删除',
		method: 'POST',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}address/del`,
	},
	ADDRESSDEFAULT: {
		domain: ROOT_URL,
		apiUrl: 'address/default',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}address/default`,
		remark: '默认收货地址',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}address/default`,
	},
	// ******** Order ********
	ORDERLIST: {
		domain: ROOT_URL,
		apiUrl: 'order/list',
		author: '孙泉',
		fetchUrl: `${ROOT_URL}order/list`,
		remark: '订单列表',
		method: 'GET',
		tableName: 'ez_store',
		needLogin: true,
		showLoading: false,
		developer: girl1,
		mock: false,
		mockFetchUrl: `${MOCK_ROOT_URL}order/list`,
	},
}
