module.exports = {
    brand_primary: "#FF585D",
    brand_primary_tap: "#fdc253",
    primary_button_fill: "#FF585D",
    primary_button_fill_tap: "#fdc253",
    ghost_button_color: "#FF585D",
    ghost_button_fill_tap: "#fdc253",
    button_font_size:16,
    button_height:44,
    list_item_height:50,
    tabs_height:44,
    color_text_base:"#333333",
    border_color_base:"#eaeaea",
    search_bar_fill: "#fff",
    search_color_icon: "#ccc",
};
