export const USER_STATUS_CHANGE = 'USER_STATUS_CHANGE'; // 用户状态改变
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'; // 更新用户信息
export const GET_USER_MIXEDSTATENUM_DATA = 'GET_USER_MIXEDSTATENUM_DATA'; // 获取用户个人中心混合的各种状态数量数据
export const UPDATE_USER_INFO_LOADING = 'UPDATE_USER_INFO_LOADING'; // 更新用户信息开始等待
export const GET_UNREAD_ALL_COUNT = 'GET_UNREAD_ALL_COUNT'; // 获得用户未读消息数量
export const GET_USER_CARD_LIST = 'GET_USER_CARD_LIST'; // 获取用户卡片列表
export const SET_UNREAD_MESSAGE_NUMBER = 'SET_UNREAD_MESSAGE_NUMBER'; // 设置未读消息数量
export const GET_USER_SENDOLDPHONESMS = 'GET_USER_SENDOLDPHONESMS'// 原手机号获取验证码
export const GET_USER_GET_MYMEMBER = 'GET_USER_GET_MYMEMBER'// 获得我的客户数据
export const GET_USER_LEVEL_DETAIL = 'GET_USER_LEVEL_DETAIL'// 获取会员等级信息
